### ISSUE TITLE
Error starting nodejs program after compile.

### ISSUE THREAD

**Issue by SamKingDev** [Timeraa/TS-DevScript#11]
I get the following error every time I try to start-up ts-devscript with or without administrator perms on Windows 11. I get this error after it has compiled the program fully.

```
Error: spawn C:\Program Files\nodejs\node.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Timeraa** [comment]
That's odd, it works fine for me on W11, maybe your node installation is broken?
